"""Suno V4 music generation API client."""

from .client import SunoClient
from .models import (
    SunoConcatRequest,
    SunoCoverRequest,
    SunoCreateRequest,
    SunoCreateWithLyricsRequest,
    SunoDescribeMusicRequest,
    SunoExtendRequest,
    SunoMIDIRequest,
    SunoMIDIResponse,
    SunoMusicResponse,
    SunoPersonaMusicRequest,
    SunoPersonaRequest,
    SunoPersonaResponse,
    SunoStemsBasicResponse,
    SunoStemsFullResponse,
    SunoTaskResponse,
    SunoUploadResponse,
    SunoWAVRequest,
    SunoWAVResponse,
)

__all__ = [
    "SunoClient",
    "SunoCreateRequest",
    "SunoCreateWithLyricsRequest",
    "SunoDescribeMusicRequest",
    "SunoExtendRequest",
    "SunoConcatRequest",
    "SunoCoverRequest",
    "SunoStemsBasicResponse",
    "SunoStemsFullResponse",
    "SunoPersonaRequest",
    "SunoPersonaResponse",
    "SunoPersonaMusicRequest",
    "SunoUploadResponse",
    "SunoWAVRequest",
    "SunoWAVResponse",
    "SunoMIDIRequest",
    "SunoMIDIResponse",
    "SunoMusicResponse",
    "SunoTaskResponse",
]
